### ISSUE TITLE
Crashing on Startup?

### ISSUE THREAD

**Issue by wunderbutt** [KerberX/PrivateProfileRedirector#2]
Seems to be crashing when I start up my game, not sure what's going on, but think I have a log here.

https://mega.nz/#!jE5RgACL!YlXkevteo0TFPiUV4foRJId9Pmv2Ama7PfG5uhPjybM

**Comment by Karandra** [comment]
So, this is Fallout 4. I don't see anything obvious in the log. Probably incompatibility with one of your mods. Post your mod list. Also, try without ENB.

**Comment by wunderbutt** [comment]
Removing ENB didn't seem to fix it, so I checked my mod list. I do have a lot of mods, but disabling Kill Tips and Hitsound UI by tooun let me load my game normally and much faster thanks to your mod.

**Comment by Karandra** [comment]
Ok, I'll look into these mods to see what causing the crash.
- Kill Tips
- Hitsound UI
